package unitconverter;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

public class ConverterForm extends javax.swing.JFrame {

    UnitGroup selectedUnitGroup = null;

    public ConverterForm() {
        initComponents();

        try {
            UnitGroup mass = new UnitGroup("Mass",
                    new String[]{"g", "kg", "lbs", "t"},
                    new double[]{1, 1000, 453.59237, 1000000});
            UnitGroup length = new UnitGroup("Legth",
                    new String[]{"mm", "cm", "m", "km", "inch", "yard", "mile"},
                    new double[]{1, 10, 1000, 1000000, 25.4, 914.4, 1609344});
            UnitGroup energy = new UnitGroup("Energy",
                    new String[]{"J", "cal", "kWh"},
                    new double[]{1, 4.184, 3600000 });
            UnitGroup power = new UnitGroup("Power", 
                    new String[]{"W", "hp", "fppm"}, 
                    new double[]{1, 745.699872, 0.0225969658});
            UnitGroup volume = new UnitGroup("Volume", 
                    new String[]{"cubic cm", "cubic dm", "cubic m", "l", "gallon", "barrel"}, 
                    new double[]{1, 1000, 1000000, 1000, 3785.41178, 119240.471});
            
            CurrencyLoader currencyLoader = new CurrencyLoader();
            currencyLoader.loadCurrencies();
            
            UnitGroup currency = new UnitGroup("Currency",
                    currencyLoader.getCurrencies(),
                    currencyLoader.getExchangeRates()
            );

            unitComboBox.addItem(mass);
            unitComboBox.addItem(length);
            unitComboBox.addItem(energy);
            unitComboBox.addItem(power);
            unitComboBox.addItem(volume);
            unitComboBox.addItem(currency);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitComboBox = new javax.swing.JComboBox();
        firstUnitComboBox = new javax.swing.JComboBox();
        secondUnitComboBox = new javax.swing.JComboBox();
        firstUnitTextField = new javax.swing.JTextField();
        secondUnitTextFiled = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();
        switchUnitsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unit Converter 3000");
        setResizable(false);

        unitComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitComboBoxItemStateChanged(evt);
            }
        });

        firstUnitComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstUnitComboBoxItemStateChanged(evt);
            }
        });

        secondUnitComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondUnitComboBoxItemStateChanged(evt);
            }
        });

        secondUnitTextFiled.setEditable(false);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        switchUnitsButton.setText("Swich Units");
        switchUnitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchUnitsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstUnitTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstUnitComboBox, 0, 184, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(secondUnitComboBox, 0, 178, Short.MAX_VALUE)
                            .addComponent(secondUnitTextFiled)))
                    .addComponent(switchUnitsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondUnitTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switchUnitsButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            selectedUnitGroup = (UnitGroup) evt.getItem();

            firstUnitComboBox.removeAllItems();
            secondUnitComboBox.removeAllItems();

            for (String unit : selectedUnitGroup.getUnits()) {
                firstUnitComboBox.addItem(unit);
                secondUnitComboBox.addItem(unit);
            }
        }
    }//GEN-LAST:event_unitComboBoxItemStateChanged

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        try {
            double value = Double.parseDouble(firstUnitTextField.getText());

            double converted = selectedUnitGroup.convert(value,
                    firstUnitComboBox.getSelectedIndex(),
                    secondUnitComboBox.getSelectedIndex());

            secondUnitTextFiled.setText(converted + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid number in input field");
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void firstUnitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstUnitComboBoxItemStateChanged
        secondUnitTextFiled.setText("");
    }//GEN-LAST:event_firstUnitComboBoxItemStateChanged

    private void secondUnitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondUnitComboBoxItemStateChanged
        secondUnitTextFiled.setText("");
    }//GEN-LAST:event_secondUnitComboBoxItemStateChanged

    private void switchUnitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchUnitsButtonActionPerformed
        int firstSelectedIndex = firstUnitComboBox.getSelectedIndex();
        
        firstUnitComboBox.setSelectedIndex(secondUnitComboBox.getSelectedIndex());
        secondUnitComboBox.setSelectedIndex(firstSelectedIndex);
    }//GEN-LAST:event_switchUnitsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JComboBox firstUnitComboBox;
    private javax.swing.JTextField firstUnitTextField;
    private javax.swing.JComboBox secondUnitComboBox;
    private javax.swing.JTextField secondUnitTextFiled;
    private javax.swing.JButton switchUnitsButton;
    private javax.swing.JComboBox unitComboBox;
    // End of variables declaration//GEN-END:variables
}
